apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql2
  template:
    metadata:
      labels:
        app: sql2
    spec:
      containers:
      - name: sql2
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database-name
        - name: MSSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: MSSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: db-data
          mountPath: /var/opt/mssql
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc