apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: votre-image-docker
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: postgres # Nom du service PostgreSQL
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: database-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
