apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: mysql:8
        command: ["sh", "-c", "mysql -h mysql-service -u root -ppassword < /init.sql"]
        volumeMounts:
        - name: init-script
          mountPath: /init.sql
          subPath: init.sql
      restartPolicy: OnFailure
      volumes:
      - name: init-script
        configMap:
          name: db-init-script
