# Étape 1: Utiliser une image de base officielle Node.js
FROM node:16

# Étape 2: Créer et définir le répertoire de travail
WORKDIR /app

# Étape 3: Copier le fichier package.json et package-lock.json pour installer les dépendances
COPY package*.json ./

# Étape 4: Installer les dépendances de l'application
RUN npm install

# Étape 5: Copier le code source dans le conteneur
COPY . .

# Étape 6: Exposer le port que l'application va utiliser
EXPOSE 80

# Étape 7: Démarrer l'application
CMD ["npm", "start"]
